project:
  type: website
  output-dir: docs

website:
  title: "Katherine N. Slain, D.O."
  navbar:
    pinned: true
    right:
      - text: "About Me"
      - file: about.qmd
      - icon: github
        href: https://github.com/
      - icon: twitter
        href: https://twitter.com
format:
  html:
    theme: solar
    css: styles.css

editor: visual